
 
#include <math.h>  
#include <stdlib.h>


#include "arm_math.h" 		//CMSIS DSP library header
 
/* ---------------------------------------------------------------------- 
* Defines each of the tests performed 
* ------------------------------------------------------------------- */ 

 
 
/* ---------------------------------------------------------------------- 
* Test input data for Floating point sin_cos example for 32-blockSize 
* Generated by the MATLAB randn() function 
* ------------------------------------------------------------------- */ 
 

 
/* ---------------------------------------------------------------------- 
* Declare Global variables  
* ------------------------------------------------------------------- */ 

float32_t  setPoint=0;  
float32_t  motorIn =0;  
float32_t  error =0;
float32_t  motorOut =0;
arm_pid_instance_f32 S;
float time =0;

float transferFunction (float in,float time);
/* ---------------------------------------------------------------------- 
* Max magnitude FFT Bin test 
* ------------------------------------------------------------------- */ 

arm_status status; 
 
int32_t main(void){ 
int i;
S.Kp = 1;			  								
S.Ki = 1;
S.Kd = 1;
	setPoint = 10;
	
	arm_pid_init_f32	(	&S,0);
 
    while(1){
		error = setPoint-motorOut;												//calculate the error
		motorIn = arm_pid_f32	(	&S,error ); 							//Run the PID algorithm
		motorOut = transferFunction(motorIn,time);				// Simulate the transfer function
		time += 1;																				//Increment the pseduo time index
		for(i=0;i<100000;i++){														//delay loop
			;	
		}	
}} 

float transferFunction (float in,float time){
float out;
float timeConst;
timeConst = (time/100)* -1;
out =  in*(1-(pow(2.1718,timeConst)));	
return (out);
}

